### PR TITLE
Refactor of code.py

### PR DESCRIPTION
**Pull request by jfurcean**
Refactored `code.py` to simplify the `while True:` loop. This needs to be fully tested. I did an initial test moving a single button and led on each pin.

### CODE REVIEW

**Comment by pjgpetecodes** [comment]
Thanks!! I'll give it a test and sort out the merge tomorrow...

Thanks!

**Review by pjgpetecodes — CHANGES_REQUESTED** [review]
Thanks very much for the refactor... Oddly tho, even though the code looks great, it doesn't seem to change scenes very well... 

I tried changing the actual key press stuff to use the same `press` and `release` actions and added a debounce delay at the end of the while loop too, but pressing the buttons, although it lights the light, doesn't actually change the scene every time...

The original code seems to work on each button press... With this, I have to press the button multiple times and sometimes it just doesn't work...

Any chance you could take a look?

Cheers!

**Comment by jfurcean** [comment]
Yes, I am hoping to get mine wired today or tomorrow and will test more and see if I can find the issue.

**Comment by pjgpetecodes** [comment]
Fantastic! Definitely let me know how you get on with your build... Photos etc! Thanks so much!

**Comment by jfurcean** [comment]
Hmm? I wired mine up and tested it (without the LEDs). I am not seeing any issues. I'm not sure if it could be a difference in operating systems? I wired mine up and tested it. I ended up removing the `time.sleep()` that I initially had after the `keyboard.send` command. I don't think it is needed and this could have been causing your issues.

**Comment by pjgpetecodes** [comment]
Interesting... Are you on Windows or Mac?

**Comment by jfurcean** [comment]
I'm on a Mac and that is why the send command might have worked for me and not you. I have updated it to use the `keyboard.press()`, `time.sleep()` and `keyboard.release()` functions to try to fix the issue.

**Pull request merged**
